[
    {
        "state": "Alaska",
        "location": "Anchorage",
        "company": "David's Bridal",
        "date_filled": "4/14/23",
        "date_effective": "June-August 2023",
        "employee_count": "TBA",
    },
    {
        "state": "Alaska",
        "location": "Matanuska-Susitna Borough",
        "company": "First Student",
        "date_filled": "5/2/22",
        "date_effective": "6/30/22",
        "employee_count": "182",
    },
    {
        "state": "Alaska",
        "location": "Anchorage",
        "company": "Bean’s Cafe",
        "date_filled": "9/16/21",
        "date_effective": "9/15/21",
        "employee_count": "40",
    },
    {
        "state": "Alaska",
        "location": "Prudhoe Bay",
        "company": "Kakivik Asset Mgmt",
        "date_filled": "7/2/21",
        "date_effective": "8/31/21",
        "employee_count": "134",
    },
    {
        "state": "Alaska",
        "location": "Fairbanks, North Pole",
        "company": "First Student",
        "date_filled": "4/30/21",
        "date_effective": "6/30/21",
        "employee_count": "185",
    },
    {
        "state": "Alaska",
        "location": "Anchorage",
        "company": "GCI Communication Group",
        "date_filled": "4/12/21",
        "date_effective": "August-November 2021",
        "employee_count": "59",
    },
    {
        "state": "Alaska",
        "location": "Anchorage and 20 smaller Alaska communities, plus Boston, Mass.",
        "company": "RavnAir Group, Corvus Airlines, Hageland Aviation Services and Peninsula Aviation Services",
        "date_filled": "9/30/20*",
        "date_effective": "8/7/20",
        "employee_count": "1,234",
    },
    {
        "state": "Alaska",
        "location": "Anchorage",
        "company": "HMSHost – Ted Stevens Anchorage International Airport restaurants: Starbucks, Humpy’s Great Alaskan Alehouse, Norton Sound Seafood House, Cinnabon, Alaska Doghaus, Cream, Upper One Restaurant/Lounge, Mezzanine Bar, Anchorage Marketplace and Local Alaska Rustic Marketplace",
        "date_filled": "8/12/20",
        "date_effective": "10/15/20",
        "employee_count": "123",
    },
    {
        "state": "Alaska",
        "location": "Fairbanks",
        "company": "HMSHost – Fairbanks International Airport restaurants: The Local and Starbucks",
        "date_filled": "8/12/20",
        "date_effective": "10/15/20",
        "employee_count": "19",
    },
    {
        "state": "Alaska",
        "location": "Shemya Island",
        "company": "Chenega Security and Support Solutions LLC",
        "date_filled": "7/31/20",
        "date_effective": "9/30/20",
        "employee_count": "64",
    },
    {
        "state": "Alaska",
        "location": "Anchorage",
        "company": "Alaska Airlines",
        "date_filled": "7/31/20",
        "date_effective": "10/1/20",
        "employee_count": "331",
    },
    {
        "state": "Alaska",
        "location": "Anchorage, Fairbanks, Denali National Park and Healy",
        "company": "Holland America Group, Carnival UK, Westmark Hotels, Inc., Tour Alaska, Inc., Royal Hyway Tours, Inc., Anchorage Westmark Hotel, Escorted Tour Operations, Anchorage Transportation, Anchorage Rail Division, Fairbanks Westmark Hotel, Fairbanks Transportation, Westmark McKinley Chalet Resort, Denali Princess Wilderness Lodge, Denali Transportation Division, Healy Homestead",
        "date_filled": "5/19/20",
        "date_effective": "6/1/20",
        "employee_count": "149",
    },
    {
        "state": "Alaska",
        "location": "North Slope",
        "company": "Doyon Drilling Inc.",
        "date_filled": "5/1/20",
        "date_effective": "4/7/20 to 5/31/20",
        "employee_count": "304",
    },
    {
        "state": "Alaska",
        "location": "Bethel and other Y-K Delta communities",
        "company": "Yukon-Kuskokwim Health Corporation",
        "date_filled": "4/28/20",
        "date_effective": "4/29/20 to 5/31/20",
        "employee_count": "Up to 300",
    },
    {
        "state": "Alaska",
        "location": "Anchorage",
        "company": "Hard Rock Cafe International STP",
        "date_filled": "4/27/20",
        "date_effective": "4/13/20 to 4/27/20",
        "employee_count": "54",
    },
    {
        "state": "Alaska",
        "location": "North Slope",
        "company": "Baker Hughes",
        "date_filled": "4/27/20",
        "date_effective": "4/28/20 to 5/11/20",
        "employee_count": "63",
    },
    {
        "state": "Alaska",
        "location": "North Slope",
        "company": "Schlumberger Technology Corp.",
        "date_filled": "4/22/20",
        "date_effective": "4/22/20 to June 2020",
        "employee_count": "129",
    },
    {
        "state": "Alaska",
        "location": "Prudhoe Bay",
        "company": "Halliburton Energy Services",
        "date_filled": "4/20/20",
        "date_effective": "4/20/20",
        "employee_count": "80",
    },
    {
        "state": "Alaska",
        "location": "Anchorage",
        "company": "Crush Bistro",
        "date_filled": "4/2/20",
        "date_effective": "4/17/20",
        "employee_count": "24",
    },
    {
        "state": "Alaska",
        "location": "Anchorage",
        "company": "South Restaurant & Coffeehouse",
        "date_filled": "4/2/20",
        "date_effective": "4/17/20",
        "employee_count": "82",
    },
    {
        "state": "Alaska",
        "location": "Anchorage",
        "company": "Snow City Café",
        "date_filled": "4/2/20",
        "date_effective": "4/17/20",
        "employee_count": "37",
    },
    {
        "state": "Alaska",
        "location": "Anchorage",
        "company": "Benihana",
        "date_filled": "4/2/20",
        "date_effective": "4/16/20",
        "employee_count": "68",
    },
    {
        "state": "Alaska",
        "location": "North Slope, Kenai Peninsula, And Valdez",
        "company": "Peak Oilfield Services",
        "date_filled": "4/1/20",
        "date_effective": "4/1/20 5/31/20",
        "employee_count": "161",
    },
    {
        "state": "Alaska",
        "location": "Anchorage",
        "company": "Spenard Roadhouse",
        "date_filled": "4/1/20",
        "date_effective": "4/17/20",
        "employee_count": "77",
    },
    {
        "state": "Alaska",
        "location": "Anchorage",
        "company": "Westmark Anchorage",
        "date_filled": "3/25/20",
        "date_effective": "3/25/20",
        "employee_count": "37",
    },
    {
        "state": "Alaska",
        "location": "Anchorage",
        "company": "Alsco",
        "date_filled": "3/25/20",
        "date_effective": "3/25/20",
        "employee_count": "21",
    },
    {
        "state": "Alaska",
        "location": "Girdwood",
        "company": "Alyeska Resort",
        "date_filled": "3/18/20",
        "date_effective": "3/19/20",
        "employee_count": "616",
    },
    {
        "state": "Alaska",
        "location": "North Slope",
        "company": "British Petroleum",
        "date_filled": "12/19/19",
        "date_effective": "2/20/20",
        "employee_count": "345",
    },
    {
        "state": "Alaska",
        "location": "Anchorage",
        "company": "British Petroleum",
        "date_filled": "12/19/19",
        "date_effective": "2/20/20",
        "employee_count": "287",
    },
    {
        "state": "Alaska",
        "location": "Eielson AFB",
        "company": "AECOM",
        "date_filled": "12/6/19",
        "date_effective": "1/4/20",
        "employee_count": "160",
    },
    {
        "state": "Alaska",
        "location": "Anchorage",
        "company": "Nordstrom Anchorage",
        "date_filled": "6/26/19",
        "date_effective": "09/13/19",
        "employee_count": "173",
    },
    {
        "state": "Alaska",
        "location": "Clear, AK",
        "company": "Aleut O&M Services, LLC",
        "date_filled": "7/2/18",
        "date_effective": "8/31/18",
        "employee_count": "74",
    },
    {
        "state": "Alaska",
        "location": "Clear, AK",
        "company": "BAE Systems",
        "date_filled": "6/25/18",
        "date_effective": "8/31/18",
        "employee_count": "101",
    },
    {
        "state": "Alaska",
        "location": "Prudhoe Bay/ Anchorage",
        "company": "Mistras Group, Inc. and subsidiary Quality Services Laboratories Inc.",
        "date_filled": "1/23/18",
        "date_effective": "3/31/18",
        "employee_count": "261",
    },
    {
        "state": "Alaska",
        "location": "Fairbanks",
        "company": "Sam’s Club",
        "date_filled": "1/11/18",
        "date_effective": "Starting 3/16/18",
        "employee_count": "177",
    },
    {
        "state": "Alaska",
        "location": "Anchorage on Muldoon Road",
        "company": "Sam’s Club",
        "date_filled": "1/11/18",
        "date_effective": "Starting 3/16/18",
        "employee_count": "167",
    },
    {
        "state": "Alaska",
        "location": "Anchorage on Old Seward Hwy.",
        "company": "Sam’s Club",
        "date_filled": "1/11/18",
        "date_effective": "Starting 3/16/18",
        "employee_count": "181",
    },
    {
        "state": "Alaska",
        "location": "Anchorage",
        "company": "Sears Holdings",
        "date_filled": "1/4/18",
        "date_effective": "Starting 4/8/18",
        "employee_count": "67",
    },
    {
        "state": "Alaska",
        "location": "Kodiak",
        "company": "Kodiak Support Services, JV",
        "date_filled": "11/30/17",
        "date_effective": "12/31/17",
        "employee_count": "125",
    },
    {
        "state": "Alaska",
        "location": "Milne, Endicott, and Northstar on the North Slope",
        "company": "ASRC Energy Services",
        "date_filled": "11/28/17",
        "date_effective": "12/18/17 to 12/31/17",
        "employee_count": "92",
    },
    {
        "state": "Alaska",
        "location": "North Slope",
        "company": "Norcon",
        "date_filled": "5/12/17",
        "date_effective": "Varied",
        "employee_count": "147",
    },
    {
        "state": "Alaska",
        "location": "Soldotna, Homer & Seward",
        "company": "First Student",
        "date_filled": "4/19/17",
        "date_effective": "6/30/17",
        "employee_count": "149",
    },
    {
        "state": "Alaska",
        "location": "Anchorage/ North Slope",
        "company": "Parker Drilling",
        "date_filled": "3/21/16",
        "date_effective": "March to May 2016",
        "employee_count": "55",
    },
    {
        "state": "Alaska",
        "location": "North Slope",
        "company": "CH2M",
        "date_filled": "3/17/16",
        "date_effective": "3/31/16",
        "employee_count": "58",
    },
    {
        "state": "Alaska",
        "location": "Anchorage",
        "company": "Shell",
        "date_filled": "1/27/16",
        "date_effective": "3/31/16",
        "employee_count": "75",
    },
    {
        "state": "Alaska",
        "location": "Juneau",
        "company": "Walmart",
        "date_filled": "1/15/16",
        "date_effective": "4/15/16",
        "employee_count": "168",
    },
    {
        "state": "Alaska",
        "location": "Statewide",
        "company": "ASRC Energy Services",
        "date_filled": "11/10/15",
        "date_effective": "11/1/15 to 12/31/15",
        "employee_count": "134",
    },
    {
        "state": "Alaska",
        "location": "Anchorage/ North Slope",
        "company": "Doyon Universal Services LLC",
        "date_filled": "5/10/13",
        "date_effective": "8/15/13",
        "employee_count": "75",
    },
    {
        "state": "Alaska",
        "location": "Statewide",
        "company": "TriWest Healthcare Alliance Corp",
        "date_filled": "12/10/12",
        "date_effective": "Varied",
        "employee_count": "31",
    },
    {
        "state": "Alaska",
        "location": "North Slope",
        "company": "CH2M Hill",
        "date_filled": "12/20/12",
        "date_effective": "Varied",
        "employee_count": "380",
    },
    {
        "state": "Alaska",
        "location": "Juneau",
        "company": "Williams Inc.",
        "date_filled": "6/30/12",
        "date_effective": "9/2/12",
        "employee_count": "90",
    },
    {
        "state": "Alaska",
        "location": "Statewide",
        "company": "Hostess Brands, Inc.",
        "date_filled": "5/4/12",
        "date_effective": "11/19/12",
        "employee_count": "90",
    },
    {
        "state": "Alaska",
        "location": "Anchorage",
        "company": "United Parcel Services",
        "date_filled": "3/15/10",
        "date_effective": "various",
        "employee_count": "109",
    },
    {
        "state": "Alaska",
        "location": "Nome",
        "company": "NovaGold",
        "date_filled": "11/26/08",
        "date_effective": "11/28/08",
        "employee_count": "130",
    },
    {
        "state": "Alaska",
        "location": "Kenai",
        "company": "Agrium U.S. Inc. Kenai Nitrogen Operations",
        "date_filled": "9/26/07",
        "date_effective": "",
        "employee_count": "140",
    },
    {
        "state": "Alaska",
        "location": "Clear",
        "company": "Arctec Services",
        "date_filled": "6/20/06",
        "date_effective": "9/30/06",
        "employee_count": "171",
    },
    {
        "state": "Alaska",
        "location": "Fort Greely",
        "company": "Chugach Alutiiq Joint Venture",
        "date_filled": "5/30/06",
        "date_effective": "6/1/06",
        "employee_count": "151",
    },
    {
        "state": "Alaska",
        "location": "Mat-Su",
        "company": "First Student",
        "date_filled": "4/10/06",
        "date_effective": "6/30/06",
        "employee_count": "102",
    },
    {
        "state": "Alaska",
        "location": "Anchorage, Eagle River, Wasilla & Soldotna",
        "company": "Johnson's Tire Service, Inc.",
        "date_filled": "2/25/06",
        "date_effective": "4/1/06",
        "employee_count": "100",
    },
]
