{
    "Texas": [
        {
            "company": "Monitronics International, Inc. dba Brinks Home",
            "date_posted": "01/06/23",
            "layoff_date": "03/03/23",
            "layoff_number": 20,
            "city": "Dallas",
        },
        {
            "company": "Information Technology Coalition Inc. (Irving)",
            "date_posted": "01/05/23",
            "layoff_date": "01/31/23",
            "layoff_number": 370,
            "city": "Irving",
        },
        {
            "company": "Southwest Key Programs-Casa Blanca",
            "date_posted": "01/09/23",
            "layoff_date": "02/14/23",
            "layoff_number": 85,
            "city": "San Antonio",
        },
        {
            "company": "TUSimple",
            "date_posted": "01/10/23",
            "layoff_date": "12/21/23",
            "layoff_number": 76,
            "city": "Dallas",
        },
        {
            "company": "Ryder Inc.",
            "date_posted": "01/11/23",
            "layoff_date": "03/18/23",
            "layoff_number": 801,
            "city": "Austin",
        },
        {
            "company": "RateGenius Loan Services, Inc.",
            "date_posted": "01/12/23",
            "layoff_date": "01/11/23",
            "layoff_number": 139,
            "city": "Austin",
        },
        {
            "company": "The Pictsweet Company",
            "date_posted": "01/16/23",
            "layoff_date": "03/17/23",
            "layoff_number": 77,
            "city": "San Antonio",
        },
        {
            "company": "Genpact LLC",
            "date_posted": "01/19/23",
            "layoff_date": "03/31/23",
            "layoff_number": 964,
            "city": "Richardson",
        },
        {
            "company": "State Farm at City Line Building 1-4",
            "date_posted": "01/24/23",
            "layoff_date": "03/31/23",
            "layoff_number": 125,
            "city": "Richardson",
        },
        {
            "company": "Bed Bath and Beyond (Lewisville)",
            "date_posted": "01/25/23",
            "layoff_date": "03/26/23",
            "layoff_number": 374,
            "city": "Lewisville",
        },
        {
            "company": "Service Experts",
            "date_posted": "01/25/23",
            "layoff_date": "03/10/23",
            "layoff_number": 76,
            "city": "Richardson",
        },
        {
            "company": "Sumitomo Electric Wiring Systems",
            "date_posted": "01/20/23",
            "layoff_date": "03/31/23",
            "layoff_number": 110,
            "city": "El Paso",
        },
        {
            "company": "ABM Texas General Services, Inc",
            "date_posted": "01/27/23",
            "layoff_date": "01/16/23",
            "layoff_number": 255,
            "city": "Austin",
        },
        {
            "company": "Owens-Brockway Glass Container Inc.",
            "date_posted": "01/31/23",
            "layoff_date": "01/31/23",
            "layoff_number": 90,
            "city": "Waco",
        },
        {
            "company": "Eddy Foods",
            "date_posted": "02/02/23",
            "layoff_date": "02/15/23",
            "layoff_number": 140,
            "city": "Yoakum",
        },
        {
            "company": "PTW Energy Services, Inc.",
            "date_posted": "02/02/23",
            "layoff_date": "04/03/23",
            "layoff_number": 9,
            "city": "Midland",
        },
        {
            "company": "Georgia Pacific Gypsum",
            "date_posted": "02/02/23",
            "layoff_date": "04/01/23",
            "layoff_number": 158,
            "city": "Quanah",
        },
        {
            "company": "Bedding Acquisition, LLC",
            "date_posted": "01/31/23",
            "layoff_date": "03/31/23",
            "layoff_number": 74,
            "city": "Grand Prairie",
        },
        {
            "company": "Transde,v Inc,",
            "date_posted": "01/31/23",
            "layoff_date": "01/30/23",
            "layoff_number": 83,
            "city": "Lancaster",
        },
        {
            "company": "Owens Corning Amarillo Facility",
            "date_posted": "02/07/23",
            "layoff_date": "04/04/23",
            "layoff_number": 200,
            "city": "Amarillo",
        },
        {
            "company": "Packaging Corporation of America (Woodway)",
            "date_posted": "02/07/23",
            "layoff_date": "03/28/23",
            "layoff_number": 65,
            "city": "Woodway",
        },
        {
            "company": "Skorpios Technologies, Inc.",
            "date_posted": "02/07/23",
            "layoff_date": "04/01/23",
            "layoff_number": 60,
            "city": "Austin",
        },
        {
            "company": "Misfits Market Technologies, INC (Fullfillment Center)",
            "date_posted": "02/07/23",
            "layoff_date": "04/08/23",
            "layoff_number": 121,
            "city": "Fort Worth",
        },
        {
            "company": "Walmart Store #7310",
            "date_posted": "02/08/23",
            "layoff_date": "05/19/23",
            "layoff_number": 92,
            "city": "Katy",
        },
        {
            "company": "St. Mark's Medical Center",
            "date_posted": "02/15/23",
            "layoff_date": "02/17/23",
            "layoff_number": 64,
            "city": "La Grange",
        },
        {
            "company": "Wix.com, Inc.",
            "date_posted": "02/21/23",
            "layoff_date": "04/16/23",
            "layoff_number": 100,
            "city": "Austin",
        },
        {
            "company": "TaskUs (San Antonio)",
            "date_posted": "02/16/23",
            "layoff_date": "02/24/23",
            "layoff_number": 186,
            "city": "San Antonio",
        },
        {
            "company": "Deer Park Nursing and Rehab Center LLC",
            "date_posted": "02/16/23",
            "layoff_date": "02/08/23",
            "layoff_number": 40,
            "city": "Deer Park",
        },
        {
            "company": "Boston Scientific Corporation",
            "date_posted": "02/23/23",
            "layoff_date": "04/23/23",
            "layoff_number": 120,
            "city": "Houston",
        },
        {
            "company": "TuSimple, Inc. (Hutchins)",
            "date_posted": "02/27/23",
            "layoff_date": "02/17/23",
            "layoff_number": 10,
            "city": "Hutchins",
        },
        {
            "company": "TuSimple, Inc. (Fort Worth)",
            "date_posted": "02/27/23",
            "layoff_date": "02/17/23",
            "layoff_number": 10,
            "city": "Fort Worth",
        },
        {
            "company": "SNL Distribution Services Corporation",
            "date_posted": "02/27/23",
            "layoff_date": "03/31/23",
            "layoff_number": 60,
            "city": "Denton",
        },
        {
            "company": "Interceramic San Antonio Showroom",
            "date_posted": "02/27/23",
            "layoff_date": "08/31/23",
            "layoff_number": 19,
            "city": "San Antonio",
        },
        {
            "company": "Interceramic Plano Showroom",
            "date_posted": "02/27/23",
            "layoff_date": "05/31/23",
            "layoff_number": 4,
            "city": "Plano",
        },
        {
            "company": "Interceramic Houston-Spring Showroom",
            "date_posted": "02/27/23",
            "layoff_date": "05/31/23",
            "layoff_number": 7,
            "city": "Spring",
        },
        {
            "company": "Interceramic Houston Showroom (Clay Road)",
            "date_posted": "02/27/23",
            "layoff_date": "08/31/23",
            "layoff_number": 35,
            "city": "Houston",
        },
        {
            "company": "Interceramic Corporate Office and Distribution Center",
            "date_posted": "02/27/23",
            "layoff_date": "03/31/23",
            "layoff_number": 118,
            "city": "Carrollton",
        },
        {
            "company": "Interceramic Tile & Stone Gallery",
            "date_posted": "02/28/23",
            "layoff_date": "08/31/23",
            "layoff_number": 15,
            "city": "Dallas",
        },
        {
            "company": "Interceramic Manufacturing Facility",
            "date_posted": "02/28/23",
            "layoff_date": "02/22/23",
            "layoff_number": 161,
            "city": "Garland",
        },
        {
            "company": "Interceramic Fort Worth Showroom",
            "date_posted": "02/28/23",
            "layoff_date": "05/31/23",
            "layoff_number": 12,
            "city": "Fort Worth",
        },
        {
            "company": "Interceramic Austin Showroom",
            "date_posted": "02/28/23",
            "layoff_date": "08/31/23",
            "layoff_number": 17,
            "city": "Austin",
        },
        {
            "company": "EP Lamination",
            "date_posted": "03/02/23",
            "layoff_date": "05/02/23",
            "layoff_number": 53,
            "city": "El Paso",
        },
        {
            "company": "Southwest General Hospital, LP",
            "date_posted": "03/03/23",
            "layoff_date": "05/01/23",
            "layoff_number": 827,
            "city": "San Antonio",
        },
        {
            "company": "Security Specialists, Inc (Austin)",
            "date_posted": "03/08/23",
            "layoff_date": "04/28/23",
            "layoff_number": 240,
            "city": "Austin",
        },
        {
            "company": "Penske Logistics, LLC-Keller",
            "date_posted": "03/20/23",
            "layoff_date": "05/20/23",
            "layoff_number": 152,
            "city": "Keller",
        },
        {
            "company": "Trellis Company",
            "date_posted": "03/14/23",
            "layoff_date": "04/04/23",
            "layoff_number": 105,
            "city": "Round Rock",
        },
        {
            "company": "Ibase Operations Corporation",
            "date_posted": "03/15/23",
            "layoff_date": "05/31/23",
            "layoff_number": 81,
            "city": "Austin",
        },
        {
            "company": "Saten, Inc.",
            "date_posted": "03/22/23",
            "layoff_date": "05/13/23",
            "layoff_number": 54,
            "city": "Fort Worth",
        },
        {
            "company": "Walmart #1258",
            "date_posted": "03/31/23",
            "layoff_date": "06/02/23",
            "layoff_number": 1047,
            "city": "Fort Worth",
        },
        {
            "company": "Ibex Global Solutions (San Antonio)",
            "date_posted": "04/03/23",
            "layoff_date": "06/02/23",
            "layoff_number": 227,
            "city": "San Antonio",
        },
        {
            "company": "Molecular Templates, Inc. (MTEM)",
            "date_posted": "04/04/23",
            "layoff_date": "05/29/23",
            "layoff_number": 84,
            "city": "Austin",
        },
        {
            "company": "Hunter Douglas Fabrication Company (Custom Brands Group)",
            "date_posted": "04/05/23",
            "layoff_date": "06/09/23",
            "layoff_number": 100,
            "city": "McKinney",
        },
        {
            "company": "Chalk Mountain Services of Texas LLC",
            "date_posted": "04/05/23",
            "layoff_date": "05/31/23",
            "layoff_number": 98,
            "city": "Kermit",
        },
        {
            "company": "Premier Auto Management, LLC",
            "date_posted": "04/06/23",
            "layoff_date": "06/02/23",
            "layoff_number": 12,
            "city": "El Paso",
        },
    ]
}
