state_list = [
    'alaska',
    'alabama',
    'arizona',
    'california',
    'colorado',
    'connecticut',
    'delaware',
    'florida',
    'georgia',
    'illinois',
    'massachusetts',
    'newyork',
    'ohio',
    'pennsylvania',
    'tennessee',
    'texas',
    'utah'
]